[package]
name = "state"
version = "0.1.0"
edition = "2021"

[dependencies]
shakmaty = "0.21"
once_cell = "1"
error-stack = { git = "https://github.com/hashintel/hash", rev = "a5baa2c97b528f2551e807aa7faa88c124a9942c" }
