[package]
name = "events"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
commands = { path = "../commands" }
poise.workspace = true
tracing.workspace = true
error-stack.workspace = true
